apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: juanie-art-tls
  namespace: nexusnote
spec:
  secretName: juanie-art-tls
  dnsNames:
    - juanie.art
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
