# ===========================================
# NexusNote Services
# ===========================================

---
apiVersion: v1
kind: Service
metadata:
  name: nexusnote-web
  namespace: {{ .Values.namespace }}
  labels:
    app: nexusnote-web
    {{- include "nexusnote.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  type: ClusterIP
  selector:
    app: nexusnote-web
  ports:
    - name: http
      port: {{ .Values.env.PORT | default 3000 }}
      targetPort: http
      protocol: TCP
