---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ .Values.namespace }}-issuer
  namespace: {{ .Values.namespace }}
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{ .Values.issuer.email | default "admin@juanie.art" }}
    privateKeySecretRef:
      name: {{ .Values.namespace }}-issuer-account-key
    solvers:
      - http01:
          ingress:
            class: cilium
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nexusnote-cert
  namespace: {{ .Values.namespace }}
spec:
  secretName: nexusnote-tls
  dnsNames:
    - juanie.art
  issuerRef:
    name: {{ .Values.namespace }}-issuer
    kind: Issuer
    group: cert-manager.io
