---
apiVersion: v1
kind: Service
metadata:
  name: nexusnote-web
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: nexusnote-web
  ports:
    - name: http
      port: {{ .Values.env.PORT | default "3000" }}
      targetPort: {{ .Values.env.PORT | default "3000" }}

---
apiVersion: v1
kind: Service
metadata:
  name: nexusnote-collab
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: nexusnote-collab
  ports:
    - name: collab
      port: {{ .Values.env.HOCUSPOCUS_PORT | default "1234" }}
      targetPort: {{ .Values.env.HOCUSPOCUS_PORT | default "1234" }}